/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 BlueShape.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ }) {
  const { nodes, materials } = useGLTF('/Objects/BlueShape.gltf')
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube002_Cube000.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, -0.67, 0]} scale={1.42} />
    </group>
  )
}

useGLTF.preload('/Objects/BlueShape.gltf')
