/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 PinkShape.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ }) {
  const { nodes, materials } = useGLTF('/Objects/PinkShape.gltf')
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube_Cube001.geometry} material={materials['Material.005']} rotation={[-Math.PI / 2, 0.66, -Math.PI]} scale={1.66} />
    </group>
  )
}

useGLTF.preload('/Objects/PinkShape.gltf')
