/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 YellowShape.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ }) {
  const { nodes, materials } = useGLTF('/Objects/YellowShape.gltf')
  return (
    <group dispose={null}>
      <mesh geometry={nodes.Cube001_Cube002.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0.66, 0]} />
    </group>
  )
}

useGLTF.preload('/Objects/YellowShape.gltf')
